- project:
    templates:
      - check-requirements
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - networking-generic-switch-tempest-dlm
        - networking-generic-switch-tempest-dlm-python2
    gate:
      queue: networking-generic-switch
      jobs:
        - networking-generic-switch-tempest-dlm
        - networking-generic-switch-tempest-dlm-python2
