- project:
    templates:
      - check-requirements
      - openstack-python-jobs-neutron
      - openstack-python3-train-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - networking-generic-switch-tempest-dlm
        - networking-generic-switch-tempest-dlm-python2
        # NOTE(rpittau): this is also disabled in ironic
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
            voting: false
    gate:
      queue: networking-generic-switch
      jobs:
        - networking-generic-switch-tempest-dlm
        - networking-generic-switch-tempest-dlm-python2
